apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: {{ .Values.image.name }}:{{ .Values.image.version }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.image.port }}
        {{- if .Values.env.enabled }}
        env:
        {{ range $k, $v := .Values.env }}
        - name: {{ $k }}
          value: "{{ $v }}"
        {{ end }}
        {{- end }}