apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring
  namespace: istio-system
spec:
  rules:
  - host: "grafana.cluster"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: grafana
            port:
              number: 3000
  - host: "kiali.cluster"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: kiali
            port:
              number: 20001
  - host: "prometheus.cluster"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: prometheus
            port:
              number: 9090
  - host: "jaeger.cluster"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: tracing
            port:
              number: 16686