apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.app.name }}-vs
spec:
  hosts:
  - dsm.local
  gateways:
  - {{ .Values.app.name }}-gateway
  http:
  - match:
    - uri:
        exact: /nav/
    - uri:
        regex: /nav/.*js
    - uri:
        regex: /nav/.*css
    route:
    - destination:  
        host: {{ .Values.app.name }}
